[ci] Slightly optimize optional workflows checks (#3762)
* Update optional_checks.yml

* Update get_workflow_status.py

diff --git a/.github/workflows/optional_checks.yml b/.github/workflows/optional_checks.yml
--- a/.github/workflows/optional_checks.yml
+++ b/.github/workflows/optional_checks.yml
@@ -17,9 +17,11 @@ jobs:
           submodules: false
       - name: Check that all tests succeeded
         run: |
-            workflows=("R valgrind tests")
+            workflows=("R valgrind tests;r-valgrind")
             for i in "${workflows[@]}"; do
-                python "$GITHUB_WORKSPACE/.ci/get_workflow_status.py" "$i" \
-                || { echo "The last reported status from workflow \"$i\" is failure. Commit fixes and rerun the workflow."; \
+                workflow_name=${i%;*}
+                trigger_phrase=${i#*;}
+                python "$GITHUB_WORKSPACE/.ci/get_workflow_status.py" "$trigger_phrase" \
+                || { echo "The last reported status from workflow \"$workflow_name\" is failure. Commit fixes and rerun the workflow."; \
                 exit -1; }
             done
