fail builds producing more than 1 NOTE

diff --git a/.github/workflows/r_package.yml b/.github/workflows/r_package.yml
--- a/.github/workflows/r_package.yml
+++ b/.github/workflows/r_package.yml
@@ -317,7 +317,11 @@ jobs:
           echo ""
           cat lightgbm.Rcheck/00install.out
           echo ""
-          # allowing NOTEs, because of this one in the clang images:
+          if grep -q -E "WARNING|ERROR" lightgbm.Rcheck/00check.log; then
+              echo "WARNINGs, or ERRORs have been found by R CMD check"
+              exit 1
+          fi
+          # allowing the following NOTEs (produced by default in the clang images):
           #
           #   * checking compilation flags used ... NOTE
           #       Compilation used the following non-portable flag(s):
@@ -326,8 +330,14 @@ jobs:
           # even though CRAN itself sets that:
           # https://www.stats.ox.ac.uk/pub/bdr/Rconfig/r-devel-linux-x86_64-fedora-clang
           #
-          if grep -q -E "WARNING|ERROR" lightgbm.Rcheck/00check.log; then
-              echo "WARNINGs, or ERRORs have been found by R CMD check"
+          ALLOWED_CHECK_NOTES=1
+          NUM_CHECK_NOTES=$(
+              cat lightgbm.Rcheck/00install.out \
+              | grep -e '^Status: .* NOTE.*' \
+              | sed 's/[^0-9]*//g'
+          )
+          if [[ ${NUM_CHECK_NOTES} -gt ${ALLOWED_CHECK_NOTES} ]]; then
+              echo "Found ${NUM_CHECK_NOTES} NOTEs from R CMD check. Only ${ALLOWED_CHECK_NOTES} are allowed"
               exit 1
           fi
   all-r-package-jobs-successful:
