revert temporary testing changes

diff --git a/.github/workflows/r_package.yml b/.github/workflows/r_package.yml
--- a/.github/workflows/r_package.yml
+++ b/.github/workflows/r_package.yml
@@ -29,100 +29,100 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          # ################
-          # # CMake builds #
-          # ################
-          # - os: ubuntu-latest
-          #   task: r-package
-          #   compiler: gcc
-          #   r_version: 3.6
-          #   build_type: cmake
-          # - os: ubuntu-latest
-          #   task: r-package
-          #   compiler: gcc
-          #   r_version: 4.0
-          #   build_type: cmake
-          # - os: ubuntu-latest
-          #   task: r-package
-          #   compiler: clang
-          #   r_version: 3.6
-          #   build_type: cmake
-          # - os: ubuntu-latest
-          #   task: r-package
-          #   compiler: clang
-          #   r_version: 4.0
-          #   build_type: cmake
-          # - os: macOS-latest
-          #   task: r-package
-          #   compiler: gcc
-          #   r_version: 3.6
-          #   build_type: cmake
-          # - os: macOS-latest
-          #   task: r-package
-          #   compiler: gcc
-          #   r_version: 4.0
-          #   build_type: cmake
-          # - os: macOS-latest
-          #   task: r-package
-          #   compiler: clang
-          #   r_version: 3.6
-          #   build_type: cmake
-          # - os: macOS-latest
-          #   task: r-package
-          #   compiler: clang
-          #   r_version: 4.0
-          #   build_type: cmake
-          # - os: windows-latest
-          #   task: r-package
-          #   compiler: MINGW
-          #   toolchain: MINGW
-          #   r_version: 3.6
-          #   build_type: cmake
-          # - os: windows-latest
-          #   task: r-package
-          #   compiler: MINGW
-          #   toolchain: MSYS
-          #   r_version: 4.0
-          #   build_type: cmake
-          # # Visual Studio 2017
-          # - os: windows-2016
-          #   task: r-package
-          #   compiler: MSVC
-          #   toolchain: MSVC
-          #   r_version: 3.6
-          #   build_type: cmake
-          # # Visual Studio 2019
-          # - os: windows-2019
-          #   task: r-package
-          #   compiler: MSVC
-          #   toolchain: MSVC
-          #   r_version: 4.0
-          #   build_type: cmake
-          # ###############
-          # # CRAN builds #
-          # ###############
-          # - os: windows-latest
-          #   task: r-package
-          #   compiler: MINGW
-          #   toolchain: MINGW
-          #   r_version: 3.6
-          #   build_type: cran
-          # - os: windows-latest
-          #   task: r-package
-          #   compiler: MINGW
-          #   toolchain: MSYS
-          #   r_version: 4.0
-          #   build_type: cran
-          # - os: ubuntu-latest
-          #   task: r-package
-          #   compiler: gcc
-          #   r_version: 4.0
-          #   build_type: cran
-          # - os: macOS-latest
-          #   task: r-package
-          #   compiler: clang
-          #   r_version: 4.0
-          #   build_type: cran
+          ################
+          # CMake builds #
+          ################
+          - os: ubuntu-latest
+            task: r-package
+            compiler: gcc
+            r_version: 3.6
+            build_type: cmake
+          - os: ubuntu-latest
+            task: r-package
+            compiler: gcc
+            r_version: 4.0
+            build_type: cmake
+          - os: ubuntu-latest
+            task: r-package
+            compiler: clang
+            r_version: 3.6
+            build_type: cmake
+          - os: ubuntu-latest
+            task: r-package
+            compiler: clang
+            r_version: 4.0
+            build_type: cmake
+          - os: macOS-latest
+            task: r-package
+            compiler: gcc
+            r_version: 3.6
+            build_type: cmake
+          - os: macOS-latest
+            task: r-package
+            compiler: gcc
+            r_version: 4.0
+            build_type: cmake
+          - os: macOS-latest
+            task: r-package
+            compiler: clang
+            r_version: 3.6
+            build_type: cmake
+          - os: macOS-latest
+            task: r-package
+            compiler: clang
+            r_version: 4.0
+            build_type: cmake
+          - os: windows-latest
+            task: r-package
+            compiler: MINGW
+            toolchain: MINGW
+            r_version: 3.6
+            build_type: cmake
+          - os: windows-latest
+            task: r-package
+            compiler: MINGW
+            toolchain: MSYS
+            r_version: 4.0
+            build_type: cmake
+          # Visual Studio 2017
+          - os: windows-2016
+            task: r-package
+            compiler: MSVC
+            toolchain: MSVC
+            r_version: 3.6
+            build_type: cmake
+          # Visual Studio 2019
+          - os: windows-2019
+            task: r-package
+            compiler: MSVC
+            toolchain: MSVC
+            r_version: 4.0
+            build_type: cmake
+          ###############
+          # CRAN builds #
+          ###############
+          - os: windows-latest
+            task: r-package
+            compiler: MINGW
+            toolchain: MINGW
+            r_version: 3.6
+            build_type: cran
+          - os: windows-latest
+            task: r-package
+            compiler: MINGW
+            toolchain: MSYS
+            r_version: 4.0
+            build_type: cran
+          - os: ubuntu-latest
+            task: r-package
+            compiler: gcc
+            r_version: 4.0
+            build_type: cran
+          - os: macOS-latest
+            task: r-package
+            compiler: clang
+            r_version: 4.0
+            build_type: cran
           ################
           # Other checks #
           ################
@@ -183,24 +183,24 @@ jobs:
         run: |
           apt-get update
           apt-get install --no-install-recommends -y git
-      # - name: Checkout repository
-      #   uses: actions/checkout@v2.3.4
-      #   with:
-      #     fetch-depth: 5
-      #     submodules: true
-      # - name: Install packages
-      #   shell: bash
-      #   run: |
-      #     Rscript -e "install.packages(c('R6', 'data.table', 'jsonlite', 'testthat'), repos = 'https://cran.r-project.org', Ncpus = parallel::detectCores())"
-      #     sh build-cran-package.sh
-      #     Rdevel CMD INSTALL lightgbm_*.tar.gz || exit -1
-      # - name: Run tests with sanitizers
-      #   shell: bash
-      #   run: |
-      #     cd R-package/tests
-      #     Rscriptdevel testthat.R 2>&1 > ubsan-tests.log
-      #     cat ubsan-tests.log
-      #     exit $(cat ubsan-tests.log | grep --count "runtime error")
+      - name: Checkout repository
+        uses: actions/checkout@v2.3.4
+        with:
+          fetch-depth: 5
+          submodules: true
+      - name: Install packages
+        shell: bash
+        run: |
+          Rscript -e "install.packages(c('R6', 'data.table', 'jsonlite', 'testthat'), repos = 'https://cran.r-project.org', Ncpus = parallel::detectCores())"
+          sh build-cran-package.sh
+          Rdevel CMD INSTALL lightgbm_*.tar.gz || exit -1
+      - name: Run tests with sanitizers
+        shell: bash
+        run: |
+          cd R-package/tests
+          Rscriptdevel testthat.R 2>&1 > ubsan-tests.log
+          cat ubsan-tests.log
+          exit $(cat ubsan-tests.log | grep --count "runtime error")
   test-r-debian-clang:
     name: r-package (debian, R-devel, clang)
     timeout-minutes: 60
@@ -212,22 +212,22 @@ jobs:
         run: |
           apt-get update
           apt-get install --no-install-recommends -y git
-      # - name: Checkout repository
-      #   uses: actions/checkout@v2.3.4
-      #   with:
-      #     fetch-depth: 5
-      #     submodules: true
-      # - name: Install packages and run tests
-      #   shell: bash
-      #   run: |
-      #     export PATH=/opt/R-devel/bin/:${PATH}
-      #     Rscript -e "install.packages(c('R6', 'data.table', 'jsonlite', 'testthat'), repos = 'https://cran.r-project.org', Ncpus = parallel::detectCores())"
-      #     sh build-cran-package.sh
-      #     R CMD check --as-cran --run-donttest lightgbm_*.tar.gz || exit -1
-      #     if grep -q -E "NOTE|WARNING|ERROR" lightgbm.Rcheck/00check.log; then
-      #         echo "NOTEs, WARNINGs, or ERRORs have been found by R CMD check"
-      #         exit -1
-      #     fi
+      - name: Checkout repository
+        uses: actions/checkout@v2.3.4
+        with:
+          fetch-depth: 5
+          submodules: true
+      - name: Install packages and run tests
+        shell: bash
+        run: |
+          export PATH=/opt/R-devel/bin/:${PATH}
+          Rscript -e "install.packages(c('R6', 'data.table', 'jsonlite', 'testthat'), repos = 'https://cran.r-project.org', Ncpus = parallel::detectCores())"
+          sh build-cran-package.sh
+          R CMD check --as-cran --run-donttest lightgbm_*.tar.gz || exit -1
+          if grep -q -E "NOTE|WARNING|ERROR" lightgbm.Rcheck/00check.log; then
+              echo "NOTEs, WARNINGs, or ERRORs have been found by R CMD check"
+              exit -1
+          fi
   all-successful:
     # https://github.community/t/is-it-possible-to-require-all-github-actions-tasks-to-pass-without-enumerating-them/117957/4?u=graingert
     runs-on: ubuntu-latest
