uncomment CIs

diff --git a/.github/workflows/r_package.yml b/.github/workflows/r_package.yml
--- a/.github/workflows/r_package.yml
+++ b/.github/workflows/r_package.yml
@@ -159,39 +159,39 @@ jobs:
           $env:TASK = "${{ matrix.task }}"
           conda init powershell
           & "$env:GITHUB_WORKSPACE/.ci/test_windows.ps1"
-  # test-r-sanitizers:
-  #   name: r-package (ubuntu-latest, R-devel, GCC ASAN/UBSAN)
-  #   timeout-minutes: 60
-  #   runs-on: ubuntu-latest
-  #   container: rhub/rocker-gcc-san
-  #   steps:
-  #     - name: Install Git before checkout
-  #       shell: bash
-  #       run: |
-  #         apt-get update
-  #         apt-get install --no-install-recommends -y git
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v2.3.4
-  #       with:
-  #         fetch-depth: 5
-  #         submodules: true
-  #     - name: Install packages
-  #       shell: bash
-  #       run: |
-  #         Rscript -e "install.packages(c('R6', 'data.table', 'jsonlite', 'testthat'), repos = 'https://cran.r-project.org')"
-  #         sh build-cran-package.sh
-  #         Rdevel CMD INSTALL lightgbm_*.tar.gz || exit -1
-  #     - name: Run tests with sanitizers
-  #       shell: bash
-  #       run: |
-  #         cd R-package/tests
-  #         Rscriptdevel testthat.R 2>&1 > ubsan-tests.log
-  #         cat ubsan-tests.log
-  #         exit $(cat ubsan-tests.log | grep --count "runtime error")
+  test-r-sanitizers:
+    name: r-package (ubuntu-latest, R-devel, GCC ASAN/UBSAN)
+    timeout-minutes: 60
+    runs-on: ubuntu-latest
+    container: rhub/rocker-gcc-san
+    steps:
+      - name: Install Git before checkout
+        shell: bash
+        run: |
+          apt-get update
+          apt-get install --no-install-recommends -y git
+      - name: Checkout repository
+        uses: actions/checkout@v2.3.4
+        with:
+          fetch-depth: 5
+          submodules: true
+      - name: Install packages
+        shell: bash
+        run: |
+          Rscript -e "install.packages(c('R6', 'data.table', 'jsonlite', 'testthat'), repos = 'https://cran.r-project.org')"
+          sh build-cran-package.sh
+          Rdevel CMD INSTALL lightgbm_*.tar.gz || exit -1
+      - name: Run tests with sanitizers
+        shell: bash
+        run: |
+          cd R-package/tests
+          Rscriptdevel testthat.R 2>&1 > ubsan-tests.log
+          cat ubsan-tests.log
+          exit $(cat ubsan-tests.log | grep --count "runtime error")
   all-successful:
     # https://github.community/t/is-it-possible-to-require-all-github-actions-tasks-to-pass-without-enumerating-them/117957/4?u=graingert
     runs-on: ubuntu-latest
-    needs: [test]
+    needs: [test, test-r-sanitizers]
     steps:
     - name: Note that all tests succeeded
       run: echo "🎉"
