get more logs

diff --git a/.github/workflows/r_package.yml b/.github/workflows/r_package.yml
--- a/.github/workflows/r_package.yml
+++ b/.github/workflows/r_package.yml
@@ -39,42 +39,42 @@ jobs:
           ################
           # CMake builds #
           ################
-          - os: ubuntu-latest
-            task: r-package
-            compiler: gcc
-            r_version: 3.6
-            build_type: cmake
-            container: 'ubuntu:18.04'
-          - os: ubuntu-latest
-            task: r-package
-            compiler: gcc
-            r_version: 4.3
-            build_type: cmake
-            container: 'ubuntu:22.04'
-          - os: ubuntu-latest
-            task: r-package
-            compiler: clang
-            r_version: 3.6
-            build_type: cmake
-            container: 'ubuntu:18.04'
-          - os: ubuntu-latest
-            task: r-package
-            compiler: clang
-            r_version: 4.3
-            build_type: cmake
-            container: 'ubuntu:22.04'
-          - os: macos-13
-            task: r-package
-            compiler: gcc
-            r_version: 4.3
-            build_type: cmake
-            container: null
-          - os: macos-13
-            task: r-package
-            compiler: clang
-            r_version: 4.3
-            build_type: cmake
-            container: null
+          # - os: ubuntu-latest
+          #   task: r-package
+          #   compiler: gcc
+          #   r_version: 3.6
+          #   build_type: cmake
+          #   container: 'ubuntu:18.04'
+          # - os: ubuntu-latest
+          #   task: r-package
+          #   compiler: gcc
+          #   r_version: 4.3
+          #   build_type: cmake
+          #   container: 'ubuntu:22.04'
+          # - os: ubuntu-latest
+          #   task: r-package
+          #   compiler: clang
+          #   r_version: 3.6
+          #   build_type: cmake
+          #   container: 'ubuntu:18.04'
+          # - os: ubuntu-latest
+          #   task: r-package
+          #   compiler: clang
+          #   r_version: 4.3
+          #   build_type: cmake
+          #   container: 'ubuntu:22.04'
+          # - os: macos-13
+          #   task: r-package
+          #   compiler: gcc
+          #   r_version: 4.3
+          #   build_type: cmake
+          #   container: null
+          # - os: macos-13
+          #   task: r-package
+          #   compiler: clang
+          #   r_version: 4.3
+          #   build_type: cmake
+          #   container: null
           - os: windows-latest
             task: r-package
             compiler: MINGW
@@ -122,18 +122,18 @@ jobs:
             r_version: 4.3
             build_type: cran
             container: null
-          - os: ubuntu-latest
-            task: r-package
-            compiler: gcc
-            r_version: 4.3
-            build_type: cran
-            container: 'ubuntu:22.04'
-          - os: macos-13
-            task: r-package
-            compiler: clang
-            r_version: 4.3
-            build_type: cran
-            container: null
+          # - os: ubuntu-latest
+          #   task: r-package
+          #   compiler: gcc
+          #   r_version: 4.3
+          #   build_type: cran
+          #   container: 'ubuntu:22.04'
+          # - os: macos-13
+          #   task: r-package
+          #   compiler: clang
+          #   r_version: 4.3
+          #   build_type: cran
+          #   container: null
     steps:
       - name: Prevent conversion of line endings on Windows
         if: startsWith(matrix.os, 'windows')
@@ -217,94 +217,94 @@ jobs:
           $env:COMPILER = "${{ matrix.compiler }}"
           $env:TASK = "${{ matrix.task }}"
           & "$env:GITHUB_WORKSPACE/.ci/test_windows.ps1"
-  test-r-sanitizers:
-    name: r-sanitizers (ubuntu-latest, R-devel, ${{ matrix.compiler }} ASAN/UBSAN)
-    timeout-minutes: 60
-    runs-on: ubuntu-latest
-    container: wch1/r-debug
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - r_customization: san
-            compiler: gcc
-          - r_customization: csan
-            compiler: clang
-    steps:
-      - name: Trust git cloning LightGBM
-        run: |
-          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 5
-          submodules: true
-      - name: Install packages
-        shell: bash
-        run: |
-          RDscript${{ matrix.r_customization }} -e "install.packages(c('R6', 'data.table', 'jsonlite', 'knitr', 'markdown', 'Matrix', 'RhpcBLASctl', 'testthat'), repos = 'https://cran.rstudio.com', Ncpus = parallel::detectCores())"
-          sh build-cran-package.sh --r-executable=RD${{ matrix.r_customization }}
-          RD${{ matrix.r_customization }} CMD INSTALL lightgbm_*.tar.gz || exit 1
-      - name: Run tests with sanitizers
-        shell: bash
-        run: |
-          cd R-package/tests
-          exit_code=0
-          RDscript${{ matrix.r_customization }} testthat.R >> tests.log 2>&1 || exit_code=-1
-          cat ./tests.log
-          exit ${exit_code}
-  test-r-debian-clang:
-    name: r-package (debian, R-devel, clang-${{ matrix.clang-version }})
-    timeout-minutes: 60
-    strategy:
-      fail-fast: false
-      matrix:
-        # list of versions tested in CRAN "Additional Checks":
-        # https://cran.r-project.org/web/checks/check_issue_kinds.html
-        clang-version:
-          - 16
-          - 17
-    runs-on: ubuntu-latest
-    container: rhub/debian-clang-devel
-    env:
-      DEBIAN_FRONTEND: noninteractive
-    steps:
-      - name: Install Git before checkout
-        shell: bash
-        run: |
-          apt-get update --allow-releaseinfo-change
-          apt-get install --no-install-recommends -y git
-      - name: Trust git cloning LightGBM
-        run: |
-          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 5
-          submodules: true
-      - name: install clang
-        run: |
-          ./.ci/install-clang-devel.sh ${{ matrix.clang-version }}
-      - name: Install packages and run tests
-        shell: bash
-        run: |
-          export PATH=/opt/R-devel/bin/:${PATH}
-          Rscript -e "install.packages(c('R6', 'data.table', 'jsonlite', 'knitr', 'markdown', 'Matrix', 'RhpcBLASctl', 'testthat'), repos = 'https://cran.rstudio.com', Ncpus = parallel::detectCores())"
-          sh build-cran-package.sh
-          R CMD check --as-cran --run-donttest lightgbm_*.tar.gz || exit 1
-          echo ""
-          echo "install logs:"
-          echo ""
-          cat lightgbm.Rcheck/00install.out
-          echo ""
-          if grep -q -E "NOTE|WARNING|ERROR" lightgbm.Rcheck/00check.log; then
-              echo "NOTEs, WARNINGs, or ERRORs have been found by R CMD check"
-              exit 1
-          fi
+  # test-r-sanitizers:
+  #   name: r-sanitizers (ubuntu-latest, R-devel, ${{ matrix.compiler }} ASAN/UBSAN)
+  #   timeout-minutes: 60
+  #   runs-on: ubuntu-latest
+  #   container: wch1/r-debug
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - r_customization: san
+  #           compiler: gcc
+  #         - r_customization: csan
+  #           compiler: clang
+  #   steps:
+  #     - name: Trust git cloning LightGBM
+  #       run: |
+  #         git config --global --add safe.directory "${GITHUB_WORKSPACE}"
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 5
+  #         submodules: true
+  #     - name: Install packages
+  #       shell: bash
+  #       run: |
+  #         RDscript${{ matrix.r_customization }} -e "install.packages(c('R6', 'data.table', 'jsonlite', 'knitr', 'markdown', 'Matrix', 'RhpcBLASctl', 'testthat'), repos = 'https://cran.rstudio.com', Ncpus = parallel::detectCores())"
+  #         sh build-cran-package.sh --r-executable=RD${{ matrix.r_customization }}
+  #         RD${{ matrix.r_customization }} CMD INSTALL lightgbm_*.tar.gz || exit 1
+  #     - name: Run tests with sanitizers
+  #       shell: bash
+  #       run: |
+  #         cd R-package/tests
+  #         exit_code=0
+  #         RDscript${{ matrix.r_customization }} testthat.R >> tests.log 2>&1 || exit_code=-1
+  #         cat ./tests.log
+  #         exit ${exit_code}
+  # test-r-debian-clang:
+  #   name: r-package (debian, R-devel, clang-${{ matrix.clang-version }})
+  #   timeout-minutes: 60
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       # list of versions tested in CRAN "Additional Checks":
+  #       # https://cran.r-project.org/web/checks/check_issue_kinds.html
+  #       clang-version:
+  #         - 16
+  #         - 17
+  #   runs-on: ubuntu-latest
+  #   container: rhub/debian-clang-devel
+  #   env:
+  #     DEBIAN_FRONTEND: noninteractive
+  #   steps:
+  #     - name: Install Git before checkout
+  #       shell: bash
+  #       run: |
+  #         apt-get update --allow-releaseinfo-change
+  #         apt-get install --no-install-recommends -y git
+  #     - name: Trust git cloning LightGBM
+  #       run: |
+  #         git config --global --add safe.directory "${GITHUB_WORKSPACE}"
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 5
+  #         submodules: true
+  #     - name: install clang
+  #       run: |
+  #         ./.ci/install-clang-devel.sh ${{ matrix.clang-version }}
+  #     - name: Install packages and run tests
+  #       shell: bash
+  #       run: |
+  #         export PATH=/opt/R-devel/bin/:${PATH}
+  #         Rscript -e "install.packages(c('R6', 'data.table', 'jsonlite', 'knitr', 'markdown', 'Matrix', 'RhpcBLASctl', 'testthat'), repos = 'https://cran.rstudio.com', Ncpus = parallel::detectCores())"
+  #         sh build-cran-package.sh
+  #         R CMD check --as-cran --run-donttest lightgbm_*.tar.gz || exit 1
+  #         echo ""
+  #         echo "install logs:"
+  #         echo ""
+  #         cat lightgbm.Rcheck/00install.out
+  #         echo ""
+  #         if grep -q -E "NOTE|WARNING|ERROR" lightgbm.Rcheck/00check.log; then
+  #             echo "NOTEs, WARNINGs, or ERRORs have been found by R CMD check"
+  #             exit 1
+  #         fi
   all-r-package-jobs-successful:
     if: always()
     runs-on: ubuntu-latest
-    needs: [test, test-r-sanitizers, test-r-debian-clang]
+    needs: [test]
     steps:
     - name: Note that all tests succeeded
       uses: re-actors/alls-green@v1.2.2
