[ci] [R-package] add CI jobs testing newer compilers

diff --git a/.github/workflows/r_package.yml b/.github/workflows/r_package.yml
--- a/.github/workflows/r_package.yml
+++ b/.github/workflows/r_package.yml
@@ -305,10 +305,44 @@ jobs:
               echo "NOTEs, WARNINGs, or ERRORs have been found by R CMD check"
               exit 1
           fi
+  test-r-extra-checks:
+    name: r-package (debian, R-devel, clang-${{ matrix.clang-version }})
+    timeout-minutes: 60
+    strategy:
+      fail-fast: false
+      matrix:
+        # ref: https://r-hub.github.io/containers/containers.html
+        image:
+          - "ghcr.io/r-hub/containers/gcc14:latest"
+    runs-on: ubuntu-latest
+    container: ${{ matrix.image }}
+    env:
+      DEBIAN_FRONTEND: noninteractive
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 5
+          submodules: true
+      - name: Install packages and run tests
+        shell: bash
+        run: |
+          Rscript -e "install.packages(c('R6', 'data.table', 'jsonlite', 'knitr', 'markdown', 'Matrix', 'RhpcBLASctl', 'testthat'), repos = 'https://cran.rstudio.com', Ncpus = parallel::detectCores())"
+          sh build-cran-package.sh
+          R CMD check --as-cran --run-donttest lightgbm_*.tar.gz || exit 1
+          echo ""
+          echo "install logs:"
+          echo ""
+          cat lightgbm.Rcheck/00install.out
+          echo ""
+          if grep -q -E "NOTE|WARNING|ERROR" lightgbm.Rcheck/00check.log; then
+              echo "NOTEs, WARNINGs, or ERRORs have been found by R CMD check"
+              exit 1
+          fi
   all-r-package-jobs-successful:
     if: always()
     runs-on: ubuntu-latest
-    needs: [test, test-r-sanitizers, test-r-debian-clang]
+    needs: [test, test-r-sanitizers, test-r-debian-clang, test-r-extra-checks]
     steps:
     - name: Note that all tests succeeded
       uses: re-actors/alls-green@v1.2.2
